### ISSUE TITLE
logo design for Pomotron application

### ISSUE THREAD

**Issue by harunbadilli** [mattbudde/pomotron#1]
Hi there, I designed a logo for Pomotron application. I hope you will like it. In case you like, I can send the logo files in the format you want. You can choose whatever you like in black and white.
![1](https://user-images.githubusercontent.com/34319922/37642102-00878352-2c2d-11e8-9988-81de50eedf28.png)
![2](https://user-images.githubusercontent.com/34319922/37642107-0476b2f8-2c2d-11e8-8277-257751e1cd04.png)

**Comment by mattbudde** [comment]
Hey, thanks for creating the design. Unfortunately I already have a logo that i made that everything else is designed around.
